export const LINK_LIST_REQUEST = 'LINK_LIST_REQUEST'
export const LINK_LIST_SUCCESS = 'LINK_LIST_SUCCESS'
export const LINK_LIST_FAIL = 'LINK_LIST_FAIL'

export const LINK_DETAILS_REQUEST = 'LINK_DETAILS_REQUEST'
export const LINK_DETAILS_SUCCESS = 'LINK_DETAILS_SUCCESS'
export const LINK_DETAILS_FAIL = 'LINK_DETAILS_FAIL'

export const LINK_USER_LIST_REQUEST = 'LINK_USER_LIST_REQUEST'
export const LINK_USER_LIST_SUCCESS = 'LINK_USER_LIST_SUCCESS'
export const LINK_USER_LIST_FAIL = 'LINK_USER_LIST_FAIL'

export const LINK_USER_DETAILS_REQUEST = 'LINK_USER_DETAILS_REQUEST'
export const LINK_USER_DETAILS_SUCCESS = 'LINK_USER_DETAILS_SUCCESS'
export const LINK_USER_DETAILS_FAIL = 'LINK_USER_DETAILS_FAIL'

export const LINK_DELETE_REQUEST = 'LINK_DELETE_REQUEST'
export const LINK_DELETE_SUCCESS = 'LINK_DELETE_SUCCESS'
export const LINK_DELETE_FAIL = 'LINK_DELETE_FAIL'

export const LINK_CREATE_REQUEST = 'LINK_CREATE_REQUEST'
export const LINK_CREATE_SUCCESS = 'LINK_CREATE_SUCCESS'
export const LINK_CREATE_FAIL = 'LINK_CREATE_FAIL'
export const LINK_CREATE_RESET = 'LINK_CREATE_RESET'

export const LINK_UPDATE_REQUEST = 'LINK_UPDATE_REQUEST'
export const LINK_UPDATE_SUCCESS = 'LINK_UPDATE_SUCCESS'
export const LINK_UPDATE_FAIL = 'LINK_UPDATE_FAIL'
export const LINK_UPDATE_RESET = 'LINK_UPDATE_RESET'

export const LINK_CREATE_REVIEW_REQUEST = 'LINK_CREATE_REVIEW_REQUEST'
export const LINK_CREATE_REVIEW_SUCCESS = 'LINK_CREATE_REVIEW_SUCCESS'
export const LINK_CREATE_REVIEW_FAIL = 'LINK_CREATE_REVIEW_FAIL'
export const LINK_CREATE_REVIEW_RESET = 'LINK_CREATE_REVIEW_RESET'

export const LINK_TOP_REQUEST = 'LINK_TOP_REQUEST'
export const LINK_TOP_SUCCESS = 'LINK_TOP_SUCCESS'
export const LINK_TOP_FAIL = 'LINK_TOP_FAIL'

export const LINK_UPDATE_LIKES = 'UPDATE_LIKES'
export const LINK_ERROR = 'LINK_ERROR'

export const LINK_ALL_USER_DETAILS_SUCCESS ='LINK_ALL_USER_DETAILS_SUCCESS'
export const LINK_ALL_USER_DETAILS_FAIL ='LINK_ALL_USER_DETAILS_SUCCESS'
export const  LINK_ALL_USER_DETAILS_REQUEST = 'LINK_ALL_USER_DETAILS_REQUEST'